name: Pipeline Script

on:
  workflow_dispatch:

jobs:
  safaa-model-retraining:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: Safaa/src/safaa/pipeline_dir/
#      SAFAA_SECRET: ${{ secrets.MY_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

#      - name: Fetch Copyright Content from server
#        run: |
#          python $BASE_PATH/script_for_copyrights.py

      - name: Run utility script
        run: |
          python $BASE_PATH/utility_script.py

      - name: Set artifact suffix
        run: echo "ARTIFACT_SUFFIX=$(date +%Y%m%d)_${{ github.sha }}" >> $GITHUB_ENV

      - name: Upload cleaned output
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data-${{ env.ARTIFACT_SUFFIX }}
          path: ${{ env.BASE_PATH }}/data/preprocessed_copyrights.csv

      - name: Upload Decluttered Output
        uses: actions/upload-artifact@v4
        with:
          name: decluttered-data-${{ env.ARTIFACT_SUFFIX }}
          path: ${{ env.BASE_PATH }}/data/decluttered_copyrights.csv

      - name: Upload Split Data
        uses: actions/upload-artifact@v4
        with:
          name: split-data-${{ env.ARTIFACT_SUFFIX }}
          path: |
            ${{ env.BASE_PATH }}/data/train_data.csv
            ${{ env.BASE_PATH }}/data/test_data.csv
